project/main/urls.py
from . import views
from django.urls import path

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('load-models/', views.load_models, name='load-models')
]

project/project/urls.py
from django.urls import path
from django.conf import settings
from django.contrib import admin
from django.urls.conf import include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

project/main/models.py
from django.db import models
from django.conf import settings
import django.utils.timezone as timezone
from .scripts.cars_bg import CarsBgClass


TRANSMISSION_TYPE_CHOICES = [
    ('', 'Избери'),
    ('Автоматични', 'Автоматични'),
    ('Ръчни', 'Ръчни')
]

CATEGORY_CHOICES = [
    ('', 'Избери'),
    ('Седан', 'Седан'),
    ('Хечбек', 'Хечбек'),
    ('Комби', 'Комби'),
    ('Купе', 'Купе'),
    ('Кабрио', 'Кабрио'),
    ('Джип', 'Джип'),
    ('Пикап', 'Пикап'),
    ('Ван', 'Ван')
]

FUEL_TYPE_CHOICES = [
    ('', 'Избери'),
    ('Бензин', 'Бензин'),
    ('Дизел', 'Дизел')
]

YEAR_CHOICES = [
    ('', 'Избери'),
]

MONTH_CHOICES = [
    ('', 'Избери'),
    ('Януари', 'Януари'),
    ('Февруари', 'Февруари'),
    ('Март', 'Март'),
    ('Април', 'Април'),
    ('Май', 'Май'),
    ('Юни', 'Юни'),
    ('Юли', 'Юли'),
    ('Август', 'Август'),
    ('Септември', 'Септември'),
    ('Октомври', 'Октомври'),
    ('Ноември', 'Ноември'),
    ('Декември', 'Декември')
]

DOORS_TYPE_CHOICES = [
    ('', 'Избери'),
    ('2/3', '2/3'),
    ('4/5', '4/5')
]

COLOR_CHOICES = [
    ('', 'Избери'),
    ('Бежов', 'Бежов'),
    ('Бордо', 'Бордо'),
    ('Бял', 'Бял'),
    ('Виолетов', 'Виолетов'),
    ('Жълт', 'Жълт'),
    ('Зелен', 'Зелен'),
    ('Кафяв', 'Кафяв'),
    ('Оранжев', 'Оранжев'),
    ('Сив', 'Сив'),
    ('Сребърен', 'Сребърен'),
    ('Червен', 'Червен'),
    ('Черен', 'Черен'),
    ('Лилав', 'Лилав'),
    ('Розов', 'Розов'),
    ('Светло зелен', 'Светло зелен'),
    ('Светло син', 'Светло син'),
    ('Тъмно зелен', 'Тъмно зелен'),
    ('Тъмно сив', 'Тъмно сив'),
    ('Тъмно син', 'Тъмно син')
]

EURO_STANDART_CHOICES = [
    ('', 'Избери'),
    ('EURO 1', 'EURO 1'),
    ('EURO 2', 'EURO 2'),
    ('EURO 3', 'EURO 3'),
    ('EURO 4', 'EURO 4'),
    ('EURO 5', 'EURO 5'),
    ('EURO 6', 'EURO 6')
]


def create_year_choices(from_year, to_year):
    for year in range(from_year, to_year):
        YEAR_CHOICES.append((str(year), str(year)))


current_year = timezone.now().year
create_year_choices(1990, current_year + 1)


class Brand(models.Model):
    brand = models.CharField(max_length=50)

    def __str__(self):
        return self.brand


class Model(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    model = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.brand} - {self.model}'


class Car(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    category = models.CharField(
        choices=CATEGORY_CHOICES, max_length=10)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
    model = models.ForeignKey(Model, on_delete=models.SET_NULL, null=True)
    modification = models.CharField(max_length=100)
    engine_type = models.CharField(max_length=20)
    price = models.IntegerField()
    transmission_type = models.CharField(
        choices=TRANSMISSION_TYPE_CHOICES, max_length=20)
    fuel_type = models.CharField(
        choices=FUEL_TYPE_CHOICES, max_length=10)
    doors_type = models.CharField(choices=DOORS_TYPE_CHOICES, max_length=5)
    power = models.IntegerField()
    displacement = models.IntegerField()
    year = models.CharField(choices=YEAR_CHOICES, max_length=4)
    month = models.CharField(choices=MONTH_CHOICES, max_length=15)
    run = models.IntegerField()
    color = models.CharField(choices=COLOR_CHOICES, max_length=20)
    euro_standart = models.CharField(
        choices=EURO_STANDART_CHOICES, max_length=10)
    description = models.CharField(max_length=400)

    def __str__(self):
        return f'{self.brand} {self.model} - {self.price}лв.'

    def get_image_paths(self):
        images = self.image_set.all()
        image_paths = []

        for image in images:
            image_paths.append(image.image.path)

        return image_paths


class Image(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='car_pics')

    def __str__(self):
        return f'{self.car.brand} - {self.car.model} - {self.car.modification} - {self.car.price}'


class OfferSite(models.Model):
    name = models.CharField(max_length=50)
    site_url = models.URLField(max_length=100)
    offer_url = models.URLField(max_length=100)
    delete_url = models.URLField(max_length=100)
    create_url = models.URLField(max_length=100)

    def __str__(self):
        return self.name


class Offer(models.Model):
    offer_id = models.CharField(max_length=50)
    site = models.ForeignKey(OfferSite, on_delete=models.SET_NULL, null=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.car.brand} - {self.car.model} - {self.car.modification} - {self.car.price}'

project/main/forms.py
from django import forms
from .models import Brand, Model, Car


IMAGES_NUMBER = 9


class CarModelForm(forms.ModelForm):
    brand = forms.ModelChoiceField(
        Brand.objects.all(), label='Марка', empty_label='Избери')
    images = forms.ImageField(required=False,
                              widget=forms.ClearableFileInput(attrs={'multiple': True, 'hidden': ''}))

    class Meta:
        model = Car
        fields = ['category', 'brand', 'model', 'modification', 'engine_type', 'price',
                  'transmission_type', 'fuel_type', 'doors_type', 'power', 'displacement', 'year',
                  'month', 'run', 'color', 'euro_standart', 'description', 'images']
        widgets = {
            'description': forms.Textarea
        }

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['model'].empty_label = 'Избери'

        if not self.is_valid():
            self.fields['model'].queryset = Model.objects.none()

        if 'brand' in self.data:
            try:
                brand_id = int(self.data.get('brand'))
                self.fields['model'].queryset = Model.objects.filter(
                    brand=brand_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['model'].queryset = self.instance.brand.model_set

project/main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Model, Image
from .forms import CarModelForm, IMAGES_NUMBER


def home(request):
    return render(request, 'main/home.html')


@login_required
def create(request):
    if request.method == 'POST' and request.is_ajax():
        form = CarModelForm(request.POST, request.FILES)

        if form.is_valid():
            form.instance.user = request.user
            instance = form.save()

            for image in request.FILES.getlist('images'):
                Image.objects.create(car=instance, image=image)

        else:
            return JsonResponse(form.errors)
    else:
        form = CarModelForm()

    context = {
        'form': form,
        'images_number_list': range(IMAGES_NUMBER)
    }

    return render(request, 'main/create.html', context)


def load_models(request):
    brand_id = request.GET.get('brand_id')

    if brand_id != '':
        models = Model.objects.filter(brand=brand_id)
    else:
        models = Model.objects.none()

    context = {
        'models': models
    }

    return render(request, 'main/models_dropdown_options.html', context)

project/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    {% block head %}
    {% endblock head %}
    <link rel="stylesheet" href="{% static 'main/styles/base.css' %}">
    <title>EasyCarUpload</title>
</head>

<body>
    <div class="grid-wrapper">
        <header>
            <nav>
                <ul>
                    <li>Home</li>
                    <li>About</li>
                    <li>Contact</li>
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
        <footer>Footer</footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'main/js/base.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
</body>

</html>

project/main/templates/main/create.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css"
    integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock head %}

{% block content %}
<div class="forms-wrapper">
    <form action="{% url 'main:create' %}" class="form-flex" id="createForm" method="post"
        data-models-url="{% url 'main:load-models' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% for field in form %}
        <div class="input-select-wrapper">
            {% if field.name != 'images' %}
            {{ field.label_tag }}
            {% endif %}
            {{ field }}
            <ul class="errorlist">
            </ul>
        </div>
        {% endfor %}

        <div class="grid-images-wrapper">
            {% include 'main/images_input.html' %}
        </div>

        <button type="submit" class="submit-button">Submit</button>
    </form>
</div>
{% endblock content %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"
    integrity="sha512-NqYds8su6jivy1/WLoW8x1tZMRD7/1ZfhWG/jcRQLOzV1k1rIODCpMgoBnar5QXshKJGV7vi0LXLNXPoFsM5Zg=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function () {
        $('select').niceSelect();
    })
</script>
{% endblock scripts %}

project/main/templates/main/home.html
{% extends 'main/base.html' %}
{% block content %}
{% endblock content %}

project/main/templates/main/images_input.html
{% load static %}
{% for i in images_number_list %}
<div class="single-image-wrapper" style="display: none;">
    <a href="#" onclick="removeImage($(this).parent()); return false;" class="delete-button">
        <img src="{% static 'main/svgs/cross.svg' %}" class="cross-svg" alt="Cross Icon">
    </a>
    <img class="inputed-image" image-number="{{ i }}" src="" alt="Image">
</div>
<label class="single-image-wrapper" for="id_images">
    <img src="{% static 'main/svgs/camera.svg' %}" class="camera-svg" alt="Camera Icon">
</label>
{% endfor %}

project/main/templates/main/models_dropdown_options.html
<option value="">Избери</option>
{% for model in models %}
<option value="{{ model.pk }}">{{ model.model }}</option>
{% endfor %}